### ISSUE TITLE
Mithusa needs to add a math equation 

### ISSUE THREAD

**Issue by sandy214a** [maxSIMhealth/GEN#429]
These are the instructions:
Text box field for participants to write how many attempts they did
An equation to calculate 50% of the number (X) they entered in the text box above 
Instructions for participants to practice an additional X attempts they took last on IO skill

Basically we need to have a box where the student input the number of times they practiced and from that box we have to calculate 50%

**Comment by andreibosco** [comment]
After today's meeting it was decided that this won't have to be implemented and that the participants will answer the number of times practiced via quiz.
